# Generated by Django 3.2.6 on 2021-11-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='time',
        ),
    ]
