# Generated by Django 3.2.6 on 2021-11-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211103_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='price',
            new_name='start_price',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='max_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='number_of_bidder',
        ),
    ]
