# Generated by Django 3.2.6 on 2021-11-07 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_user_bids_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='auctions',
            name='have_bids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
